name: upload files on s3
run-name: upload files on s3
on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build
